//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id_tic { get; set; }
        public Nullable<int> Id_place { get; set; }
        public Nullable<int> Id_relation1 { get; set; }
        public Nullable<int> Id_relation2 { get; set; }
    
        public virtual Relation Relation { get; set; }
        public virtual Relation Relation1 { get; set; }
        public virtual SittingPlace SittingPlace { get; set; }
    }
}
