//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInfo
    {
        public Nullable<int> Nr_car { get; set; }
        public int Nr_siting { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> timeleave { get; set; }
        public string FromStation { get; set; }
        public Nullable<System.DateTime> TimeCome { get; set; }
        public string ToStation { get; set; }
        public Nullable<double> km { get; set; }
    }
}
